// mobile/app/onboarding.tsx
﻿import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { router } from 'expo-router'
import { listBooks, type Book } from '@/api/client'
import { VOCAB_STORE, setOnboarded, setDailyGoal, setStudySettings, setCurrentBook } from '@/stores/vocabulary'
import { authOnboard } from '@/api/auth'
import { colors, spacing } from '@/theme'

const GOAL_OPTIONS = [20, 30, 50]

type OnboardStep = 'book' | 'goal' | 'trial'

export default function OnboardingScreen() {
  const [step, setStep] = useState<OnboardStep>('book')
  const [books, setBooks] = useState<Book[]>([])
  const [selectedBook, setSelectedBook] = useState('ket')
  const [dailyGoal, setDailyGoal] = useState(30)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    listBooks().then(r => setBooks(r.data || [])).finally(() => setLoading(false))
  }, [])

  const nextStep = () => {
    if (step === 'book') {
      setCurrentBook(selectedBook)
      setStep('goal')
    } else if (step === 'goal') {
      setDailyGoal(dailyGoal)
      setStudySettings({ wordsPerGroup: 10, groupCount: 1 })
      setStep('trial')
    }
  }

  const finish = async () => {
    try { await authOnboard() } catch {}
    setOnboarded(true)
    router.replace('/home')
  }

  const startTrial = async () => {
    setCurrentBook(selectedBook)
    setStudySettings({ wordsPerGroup: 10, groupCount: 1, sessionMode: 'smart' })
    try { await authOnboard() } catch {}
    setOnboarded(true)
    router.replace('/recognition')
  }

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* Progress dots */}
      <View style={styles.dotsRow}>
        {(['book', 'goal', 'trial'] as OnboardStep[]).map((s, i) => (
          <View key={s} style={[styles.dot, step === s && styles.dotActive]} />
        ))}
      </View>

      {step === 'book' && (
        <>
          <Text style={styles.title}>选择考试目标</Text>
          <Text style={styles.subtitle}>我们将为你推荐对应的词汇书</Text>
          {loading ? <ActivityIndicator color={colors.primary} style={{ marginTop: 20 }} /> : (
            <View style={styles.bookList}>
              {books.map(book => (
                <Pressable key={book.code} onPress={() => setSelectedBook(book.code)} style={[styles.bookItem, selectedBook === book.code && styles.bookItemSelected]}>
                  <Text style={styles.bookName}>{book.name}</Text>
                  <Text style={styles.bookLevel}>{book.level || ''} · {book.wordCount || 0}词</Text>
                </Pressable>
              ))}
            </View>
          )}
        </>
      )}

      {step === 'goal' && (
        <>
          <Text style={styles.title}>设定每日目标</Text>
          <Text style={styles.subtitle}>坚持小目标，更容易养成习惯</Text>
          <View style={styles.goalRow}>
            {GOAL_OPTIONS.map(n => (
              <Pressable key={n} onPress={() => setDailyGoal(n)} style={[styles.goalItem, dailyGoal === n && styles.goalItemSelected]}>
                <Text style={[styles.goalNum, dailyGoal === n && { color: colors.primary }]}>{n}</Text>
                <Text style={styles.goalLabel}>词/天</Text>
              </Pressable>
            ))}
          </View>
        </>
      )}

      {step === 'trial' && (
        <>
          <Text style={styles.title}>来体验 10 词体验课</Text>
          <Text style={styles.subtitle}>快速感受智能推荐训练</Text>
          <View style={styles.trialCard}>
            <Text style={styles.trialIcon}>&#x1F4D6;</Text>
            <Text style={styles.trialBook}>{books.find(b => b.code === selectedBook)?.name || selectedBook}</Text>
            <Text style={styles.trialDesc}>10 词 · 约 3 分钟</Text>
          </View>
        </>
      )}

      {/* Buttons */}
      <View style={styles.btnRow}>
        {step !== 'book' && <Pressable onPress={() => setStep('book' as OnboardStep)}><Text style={styles.backBtn}>上一步</Text></Pressable>}
        <Pressable disabled={loading} onPress={nextStep} style={[styles.nextBtn, loading && styles.btnDisabled]}>
          <Text style={styles.nextBtnText}>{step === 'trial' ? '开始体验' : '下一步'}</Text>
        </Pressable>
      </View>

      {step === 'trial' && (
        <>
          <Pressable onPress={() => startTrial()} style={[styles.startTrialBtn, styles.mt12]}>
            <Text style={styles.startTrialText}>开始体验</Text>
          </Pressable>
          <Pressable onPress={finish} style={styles.skipLink}>
            <Text style={styles.skipText}>跳过，直接进入</Text>
          </Pressable>
        </>
      )}
    </ScrollView>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#eef2ff' },
  content: { padding: spacing.xl, paddingTop: 60, alignItems: 'center' },
  dotsRow: { flexDirection: 'row', gap: 16, marginBottom: 60 },
  dot: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#ddd' },
  dotActive: { width: 40, backgroundColor: colors.primary, borderRadius: 8 },
  title: { fontSize: 24, fontWeight: '700', color: colors.text, marginBottom: spacing.sm },
  subtitle: { fontSize: 15, color: colors.muted, marginBottom: spacing.xxl },
  bookList: { width: '100%', gap: spacing.md, marginBottom: spacing.xxl },
  bookItem: { padding: spacing.lg, borderRadius: 12, backgroundColor: colors.surface, borderWidth: 2, borderColor: 'transparent' },
  bookItemSelected: { borderColor: colors.primary, backgroundColor: '#eef2ff' },
  bookName: { fontSize: 18, fontWeight: '600', color: colors.text },
  bookLevel: { fontSize: 14, color: colors.muted, marginTop: spacing.xs },
  goalRow: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.xxl, width: '100%' },
  goalItem: { flex: 1, padding: spacing.xl, borderRadius: 12, backgroundColor: colors.surface, borderWidth: 2, borderColor: 'transparent', alignItems: 'center' },
  goalItemSelected: { borderColor: colors.primary, backgroundColor: '#eef2ff' },
  goalNum: { fontSize: 36, fontWeight: '700', color: colors.muted },
  goalLabel: { fontSize: 14, color: colors.muted, marginTop: spacing.xs },
  trialCard: { width: '100%', padding: spacing.xxl, borderRadius: 16, backgroundColor: colors.surface, alignItems: 'center', marginBottom: spacing.xl },
  trialIcon: { fontSize: 64, marginBottom: spacing.md },
  trialBook: { fontSize: 20, fontWeight: '600', color: colors.text },
  trialDesc: { fontSize: 14, color: colors.muted, marginTop: spacing.sm },
  btnRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginTop: spacing.md, gap: spacing.md },
  nextBtn: { flex: 2, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: colors.primary },
  btnDisabled: { opacity: 0.5 },
  nextBtnText: { color: colors.surface, fontWeight: '700', fontSize: 16 },
  backBtn: { flex: 1, height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: '#eee' },
  startTrialBtn: { width: '100%', height: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: colors.accent, marginTop: spacing.xl },
  startTrialText: { color: colors.surface, fontWeight: '700', fontSize: 16 },
  skipLink: { marginTop: spacing.md },
  skipText: { fontSize: 14, color: colors.muted, textDecorationLine: 'underline' },
})

// src/pages/onboarding/onboarding.vue
<template>
  <view class="container">
    <view class="progress-dots">
      <view v-for="i in 3" :key="i" :class="['dot', step >= i ? 'active' : '']" />
    </view>

    <view v-if="step === 1" class="step">
      <text class="title">选择考试目标</text>
      <text class="subtitle">我们将为你推荐对应词书</text>
      <view class="book-list">
        <view
          v-for="book in books"
          :key="book.code"
          :class="['book-item', selectedBook === book.code ? 'selected' : '']"
          @tap="selectedBook = book.code"
        >
          <text class="book-name">{{ book.name }}</text>
          <text class="book-level">{{ book.level }}</text>
          <text v-if="book.isFree === false" class="book-lock">🔒</text>
        </view>
      </view>
      <button class="btn-next" @tap="nextStep">下一步</button>
    </view>

    <view v-else-if="step === 2" class="step">
      <text class="title">设定每日目标</text>
      <text class="subtitle">坚持小目标，更容易养成习惯</text>
      <view class="goal-options">
        <view
          v-for="n in goalOptions"
          :key="n"
          :class="['goal-item', dailyGoal === n ? 'selected' : '']"
          @tap="dailyGoal = n"
        >
          <text class="goal-num">{{ n }}</text>
          <text class="goal-label">词/天</text>
        </view>
      </view>
      <button class="btn-next" @tap="nextStep">下一步</button>
    </view>

    <view v-else class="step">
      <text class="title">来试试 10 词体验课</text>
      <text class="subtitle">快速感受智能推荐训练</text>
      <view class="trial-card">
        <text class="trial-icon">📚</text>
        <text class="trial-book">{{ selectedBookName }}</text>
        <text class="trial-desc">10 词认读 · 约 3 分钟</text>
      </view>
      <button class="btn-next" @tap="startTrial">开始体验</button>
      <text class="skip-link" @tap="finishOnboarding">跳过，直接进入</text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useVocabularyStore } from '@/stores/vocabulary'
import { useUserStore } from '@/stores/user'
import { authAPI } from '@/utils/api'

const vocabStore = useVocabularyStore()
const userStore = useUserStore()

const step = ref(1)
const selectedBook = ref('ket')
const dailyGoal = ref(30)
const goalOptions = [20, 30, 50]
const books = ref<Array<{ code: string; name: string; level: string; isFree?: boolean }>>([])

const selectedBookName = computed(() =>
  books.value.find(b => b.code === selectedBook.value)?.name || selectedBook.value
)

const nextStep = () => {
  if (step.value === 1) {
    vocabStore.setCurrentBook(selectedBook.value)
    uni.setStorageSync('studyGoalBook', selectedBook.value)
  }
  if (step.value === 2) {
    uni.setStorageSync('dailyGoal', dailyGoal.value)
    vocabStore.setStudySettings({ wordsPerGroup: 10, groupCount: 1 })
  }
  step.value++
}

const finishOnboarding = async () => {
  try {
    await authAPI.onboard()
    userStore.setOnboarded(true)
  } catch {
    // still proceed locally
    userStore.setOnboarded(true)
  }
  uni.switchTab({ url: '/pages/home/home' })
}

const startTrial = async () => {
  vocabStore.setCurrentBook(selectedBook.value)
  uni.setStorageSync('dailyGoal', dailyGoal.value)
  uni.setStorageSync('studyGoalBook', selectedBook.value)
  vocabStore.setStudySettings({ wordsPerGroup: 10, groupCount: 1, sessionMode: 'smart' })
  try {
    await authAPI.onboard()
    userStore.setOnboarded(true)
  } catch {
    userStore.setOnboarded(true)
  }
  uni.navigateTo({ url: '/pages/recognition/recognition?autoStart=1' })
}

onMounted(async () => {
  await vocabStore.loadBooks()
  books.value = vocabStore.books as typeof books.value
})
</script>

<style lang="scss" scoped>
.container {
  min-height: 100vh;
  background: linear-gradient(180deg, #eef2ff 0%, #f5f5f5 40%);
  padding: 60rpx 40rpx;
}

.progress-dots {
  display: flex;
  justify-content: center;
  gap: 16rpx;
  margin-bottom: 60rpx;
}

.dot {
  width: 16rpx;
  height: 16rpx;
  border-radius: 50%;
  background: #ddd;

  &.active {
    background: #667eea;
    width: 40rpx;
    border-radius: 8rpx;
  }
}

.step {
  display: flex;
  flex-direction: column;
}

.title {
  font-size: 44rpx;
  font-weight: 600;
  color: #333;
  margin-bottom: 12rpx;
}

.subtitle {
  font-size: 28rpx;
  color: #999;
  margin-bottom: 40rpx;
}

.book-list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
  margin-bottom: 40rpx;
}

.book-item {
  background: white;
  border-radius: 16rpx;
  padding: 28rpx;
  display: flex;
  align-items: center;
  border: 2rpx solid transparent;

  &.selected {
    border-color: #667eea;
    background: #eef2ff;
  }
}

.book-name {
  flex: 1;
  font-size: 32rpx;
  font-weight: 500;
  color: #333;
}

.book-level {
  font-size: 24rpx;
  color: #999;
  margin-right: 12rpx;
}

.goal-options {
  display: flex;
  gap: 20rpx;
  margin-bottom: 40rpx;
}

.goal-item {
  flex: 1;
  background: white;
  border-radius: 16rpx;
  padding: 30rpx;
  text-align: center;
  border: 2rpx solid transparent;

  &.selected {
    border-color: #667eea;
    background: #eef2ff;
  }
}

.goal-num {
  font-size: 48rpx;
  font-weight: 600;
  color: #667eea;
  display: block;
}

.goal-label {
  font-size: 24rpx;
  color: #999;
}

.trial-card {
  background: white;
  border-radius: 20rpx;
  padding: 50rpx;
  text-align: center;
  margin-bottom: 40rpx;
}

.trial-icon {
  font-size: 80rpx;
  display: block;
  margin-bottom: 20rpx;
}

.trial-book {
  font-size: 36rpx;
  font-weight: 600;
  color: #333;
  display: block;
}

.trial-desc {
  font-size: 26rpx;
  color: #999;
  margin-top: 12rpx;
  display: block;
}

.btn-next {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  border-radius: 40rpx;
  padding: 28rpx;
  font-size: 32rpx;
}

.skip-link {
  text-align: center;
  font-size: 26rpx;
  color: #999;
  margin-top: 24rpx;
}
</style>
